# VerticalFarmModel/app.py
import streamlit as st
import pandas as pd
import altair as alt
from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm

import config as cfg
from ui.styles import apply_branding, vw_section
from core.model import compute_areas, compute_sales, compute_capex, compute_opex, build_forecast
from core.schemas import FarmInputs, CropInputs, FinanceInputs, ElectricityScenario


# -----------------------------
# Page config (MUST be first Streamlit call)
# -----------------------------
st.set_page_config(
    page_title="VacuumWood Financial Model",
    layout="wide",
    initial_sidebar_state="collapsed",
)

apply_branding()


# -----------------------------
# Helpers
# -----------------------------
def eur(x: float) -> str:
    return f"€{x:,.0f}"


def payback_timeline(payback_year: int | None, horizon_years: int):
    st.markdown("#### Payback timeline")

    if payback_year is None:
        st.write(f"Payback is **not reached within {horizon_years} years** under this scenario.")
        st.progress(1.0)
        st.caption("Progress bar shows the full forecast horizon.")
        return

    py = max(1, min(int(payback_year), int(horizon_years)))
    frac = py / horizon_years
    st.write(f"Expected payback in **Year {py}** (within a {horizon_years}-year horizon).")
    st.progress(frac)


def build_investor_pdf(
    scenario_label: str,
    payback_year: int | None,
    capex_net: float,
    yearly_opex: float,
    year1_profit: float,
    npv_end: float,
    horizon_years: int,
    electricity_price_used: float,
) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4

    x0 = 2.0 * cm
    y = h - 2.2 * cm

    def bold(txt, size=14, dy=0.9):
        nonlocal y
        c.setFont("Helvetica-Bold", size)
        c.drawString(x0, y, txt)
        y -= dy * cm

    def line(txt, size=11, dy=0.7):
        nonlocal y
        c.setFont("Helvetica", size)
        c.drawString(x0, y, txt)
        y -= dy * cm

    bold("VacuumWood • Investor Summary", size=16, dy=1.0)
    line(f"Scenario: {scenario_label}", size=11, dy=0.9)
    line(f"Electricity price used: {electricity_price_used:.4f} €/kWh", size=11, dy=1.0)

    bold("Key outputs", size=13, dy=0.9)
    pb_txt = f"Year {payback_year}" if payback_year is not None else f"Not within {horizon_years} years"
    line(f"Payback: {pb_txt}")
    line(f"CAPEX (net): {eur(capex_net)}")
    line(f"Annual OPEX: {eur(yearly_opex)}")
    line(f"Year 1 profit: {eur(year1_profit)}")
    line(f"NPV (end of horizon): {eur(npv_end)}")

    y -= 0.4 * cm
    bold("Interpretation (client-facing)", size=13, dy=0.9)
    if payback_year is None:
        line("• Under this scenario, the investment does not break even within the forecast horizon.")
    else:
        line(f"• The investment is expected to break even around Year {payback_year}.")
    line("• Main driver: operating electricity cost vs annual revenue.")
    line("• Use the Electricity Optimization page to validate historical price reductions.")

    c.setFont("Helvetica", 9)
    c.drawString(x0, 1.6 * cm, "Generated by VacuumWood Financial Dashboard (Streamlit)")
    c.showPage()
    c.save()
    return buf.getvalue()


# -----------------------------
# Intro (client-facing)
# -----------------------------
st.markdown(
    """
    <div style='text-align:center; font-size:16px; color:#666; margin-top:6px; margin-bottom:14px;'>
      Baseline financial outputs for a vertical farm module.
      Use <b>Electricity Optimization</b> to explore historical Nordpool scheduling strategies.
    </div>
    """,
    unsafe_allow_html=True,
)


# -----------------------------
# Minimal assumptions (keep hidden during demo)
# -----------------------------
with st.expander("Assumptions (optional)", expanded=False):
    c1, c2, c3 = st.columns(3)

    with c1:
        length_m = st.number_input("Inner Length (m)", value=30.0, step=1.0)
        width_m = st.number_input("Inner Width (m)", value=20.0, step=1.0)
        floors = st.number_input("Number of floors", value=6, step=1, min_value=1)

    with c2:
        floor_usage_eff = st.slider("Floor usage efficiency", 0.40, 0.95, 0.75, 0.01)
        insulation = st.number_input("Insulation thickness (m)", value=0.30, step=0.01)
        height_m = st.number_input("Inner height (m)", value=2.6, step=0.1)

    with c3:
        years = st.number_input("Forecast years", value=10, step=1, min_value=1)
        discount_rate = st.number_input("Discount rate", value=0.08, step=0.01, format="%.2f")
        year1_eff = st.slider("Year 1 production efficiency", 0.50, 1.00, 0.80, 0.01)

    st.caption("In client demos, keep this closed. It’s for internal exploration only.")


# -----------------------------
# Scenario switch (Base vs Optimized)
# Reads prices from session_state (set by electricity page) with safe fallbacks.
# -----------------------------
scenario_choice = st.radio(
    "Electricity scenario",
    ["Base price", "Optimized schedule"],
    horizontal=True,
)

base_price = float(st.session_state.get("base_price_eur_kwh", 0.12))
opt_price = float(st.session_state.get("opt_price_eur_kwh", 0.09))

scenario = ElectricityScenario(
    selected="base", #if scenario_choice == "Base price" else "opt",
    base_price_eur_kwh=cfg.ELEC_PRICE_BASE,
    opt_price_eur_kwh=cfg.ELEC_PRICE_OPT,
)


# -----------------------------
# Inputs (baseline, no huge UI)
# -----------------------------
farm = FarmInputs(
    length_m=float(length_m),
    width_m=float(width_m),
    height_m=float(height_m),
    insulation_m=float(insulation),    floor_usage_eff=float(floor_usage_eff),
    floors=int(floors),
)

crops = CropInputs(
    selected=["Lettuce", "Basil"],
    shares={"Lettuce": 0.8, "Basil": 0.2},
    yields_kg_m2_yr={"Lettuce": 70.0, "Basil": 30.0},
)

fin = FinanceInputs(
    years=int(years),
    discount_rate=float(discount_rate),
    year1_eff=float(year1_eff),
    eff_gain=0.05,
)


# -----------------------------
# Compute model
# -----------------------------
areas = compute_areas(farm)
sales_df, total_sales = compute_sales(areas["total_cultivatable"], crops)
capex = compute_capex(areas["floor_area"], areas["total_cultivatable"])
opex = compute_opex(areas["total_cultivatable"], scenario)
forecast_df, payback_year = build_forecast(
    total_sales=total_sales,
    yearly_opex=opex["yearly_opex"],
    capex_net=capex["net"],
    fin=fin,
)

# Share electricity use to other pages
st.session_state["elec_use_kwh"] = float(opex["elec_use_kwh"])

annual_profit_year1 = (total_sales * fin.year1_eff) - opex["yearly_opex"]
npv_end = float(forecast_df["NPV - CAPEX (€)"].iloc[-1])


# -----------------------------
# Executive summary (client-first)
# -----------------------------
vw_section("Executive summary")

k1, k2, k3, k4, k5 = st.columns(5)
k1.metric("Payback (year)", str(payback_year) if payback_year is not None else "—")
k2.metric("CAPEX (net)", eur(capex["net"]))
k3.metric("Annual OPEX", eur(opex["yearly_opex"]))
k4.metric("Year 1 profit", eur(annual_profit_year1))
k5.metric("NPV (end of horizon)", eur(npv_end))

st.caption(
    f"Electricity price used: **{opex['price_used']:.4f} €/kWh** "
    f"({scenario_choice})"
)

msg = "Break-even not reached within the forecast horizon." if payback_year is None else f"Expected break-even occurs in year {payback_year}."
st.info(f"**What this means:** {msg}")

payback_timeline(payback_year, fin.years)


# -----------------------------
# PDF export
# -----------------------------
vw_section("Investor summary PDF")

scenario_label = "Base electricity price" if scenario.selected == "base" else "Optimized schedule electricity price"
pdf_bytes = build_investor_pdf(
    scenario_label=scenario_label,
    payback_year=payback_year,
    capex_net=float(capex["net"]),
    yearly_opex=float(opex["yearly_opex"]),
    year1_profit=float(annual_profit_year1),
    npv_end=float(npv_end),
    horizon_years=int(fin.years),
    electricity_price_used=float(opex["price_used"]),
)

st.download_button(
    "Download 1-page Investor Summary (PDF)",
    data=pdf_bytes,
    file_name="vacuumwood_investor_summary.pdf",
    mime="application/pdf",
)


# -----------------------------
# Tabs (clean client flow)
# -----------------------------
tab1, tab2, tab3 = st.tabs(["Overview", "Economics", "Forecast & cashflow"])

with tab1:
    vw_section("Farm summary")
    s1, s2, s3, s4 = st.columns(4)
    s1.metric("Floor area (m²)", f"{areas['floor_area']:,.0f}")
    s2.metric("Cultivable / floor (m²)", f"{areas['cultivable_per_floor']:,.0f}")
    s3.metric("Total cultivatable (m²)", f"{areas['total_cultivatable']:,.0f}")
    s4.metric("Floors", f"{farm.floors}")

    vw_section("Sales split (baseline)")
    left, right = st.columns([1.2, 1])

    with left:
        st.dataframe(sales_df, use_container_width=True)

    with right:
        sales_plot = sales_df.reset_index()
        sales_plot["Revenue (€)"] = sales_plot["Revenue (€)"].astype(float)
        chart = (
            alt.Chart(sales_plot)
            .mark_bar()
            .encode(
                y=alt.Y("Product:N", sort="-x"),
                x=alt.X("Revenue (€):Q", axis=alt.Axis(format=",.0f")),
                tooltip=["Product:N", alt.Tooltip("Revenue (€):Q", format=",.0f")],
            )
            .properties(height=140)
        )
        st.altair_chart(chart, use_container_width=True)

with tab2:
    vw_section("CAPEX breakdown")
    capex_rows = pd.DataFrame(
        [
            {"Item": "Building", "€": capex["build"]},
            {"Item": "Equipment", "€": capex["eq"]},
            {"Item": "Other fixed", "€": capex["other"]},
            {"Item": "Subsidy (assumed)", "€": -capex["subsidy"]},
        ]
    )
    cA, cB = st.columns([1, 1.2])
    with cA:
        st.dataframe(capex_rows, use_container_width=True, hide_index=True)
    with cB:
        cap_chart = (
            alt.Chart(capex_rows)
            .mark_bar()
            .encode(
                y=alt.Y("Item:N", sort="-x"),
                x=alt.X("€:Q", axis=alt.Axis(format=",.0f")),
                tooltip=["Item:N", alt.Tooltip("€:Q", format=",.0f")],
            )
            .properties(height=180)
        )
        st.altair_chart(cap_chart, use_container_width=True)

    vw_section("OPEX (annual)")
    opex_rows = pd.DataFrame(
        [
            {"Item": "Electricity", "€": opex["elec_cost"]},
            {"Item": "Other operating costs", "€": opex["other_opex"]},
        ]
    )
    opex_chart = (
        alt.Chart(opex_rows)
        .mark_bar()
        .encode(
            y=alt.Y("Item:N", sort="-x"),
            x=alt.X("€:Q", axis=alt.Axis(format=",.0f")),
            tooltip=["Item:N", alt.Tooltip("€:Q", format=",.0f")],
        )
        .properties(height=120)
    )
    st.altair_chart(opex_chart, use_container_width=True)
    st.caption(f"Electricity use estimate: **{opex['elec_use_kwh']:,.0f} kWh/year**")

with tab3:
    vw_section("Break-even view (NPV - CAPEX over time)")
    df = forecast_df.copy()
    df["Year"] = df["Year"].astype(int)

    line = (
        alt.Chart(df)
        .mark_line()
        .encode(
            x=alt.X("Year:Q", title="Year"),
            y=alt.Y("NPV - CAPEX (€):Q", title="€", axis=alt.Axis(format=",.0f")),
            tooltip=["Year:Q", alt.Tooltip("NPV - CAPEX (€):Q", format=",.0f")],
        )
        .properties(height=260)
    )

    zero = alt.Chart(pd.DataFrame({"y": [0]})).mark_rule().encode(y="y:Q")
    st.altair_chart(line + zero, use_container_width=True)

    vw_section("Annual net cashflow")
    bar = (
        alt.Chart(df)
        .mark_bar()
        .encode(
            x=alt.X("Year:O", title="Year"),
            y=alt.Y("Net Cashflow (€):Q", title="€", axis=alt.Axis(format=",.0f")),
            tooltip=["Year:O", alt.Tooltip("Net Cashflow (€):Q", format=",.0f")],
        )
        .properties(height=220)
    )
    st.altair_chart(bar, use_container_width=True)

    vw_section("Forecast table")
    st.dataframe(df, use_container_width=True, hide_index=True)

st.markdown("---")
st.caption("VacuumWood • Vertical Farming Financial Model")